/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AethelRouteImport } from './routes/aethel'
import { Route as ConsortiumRouteImport } from './routes/consortium'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as NewsAgenticLongHorizonReasoningRouteImport } from './routes/news.agentic-long-horizon-reasoning'
import { Route as NewsAutonomousDrugDiscoveryRouteImport } from './routes/news.autonomous-drug-discovery'
import { Route as NewsCausalInferenceQuantFinanceRouteImport } from './routes/news.causal-inference-quant-finance'
import { Route as NewsMultimodalFoundationModelsScienceRouteImport } from './routes/news.multimodal-foundation-models-science'
import { Route as ResearchAethelRouteImport } from './routes/research.aethel'
import { Route as ResearchMorbiusRouteImport } from './routes/research.morbius'
import { Route as ResearchParallaxRouteImport } from './routes/research.parallax'
import { Route as ResearchPrometheusRouteImport } from './routes/research.prometheus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AethelRoute = AethelRouteImport.update({
  id: '/aethel',
  path: '/aethel',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsortiumRoute = ConsortiumRouteImport.update({
  id: '/consortium',
  path: '/consortium',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAgenticLongHorizonReasoningRoute =
  NewsAgenticLongHorizonReasoningRouteImport.update({
    id: '/news/agentic-long-horizon-reasoning',
    path: '/news/agentic-long-horizon-reasoning',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsAutonomousDrugDiscoveryRoute =
  NewsAutonomousDrugDiscoveryRouteImport.update({
    id: '/news/autonomous-drug-discovery',
    path: '/news/autonomous-drug-discovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsCausalInferenceQuantFinanceRoute =
  NewsCausalInferenceQuantFinanceRouteImport.update({
    id: '/news/causal-inference-quant-finance',
    path: '/news/causal-inference-quant-finance',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsMultimodalFoundationModelsScienceRoute =
  NewsMultimodalFoundationModelsScienceRouteImport.update({
    id: '/news/multimodal-foundation-models-science',
    path: '/news/multimodal-foundation-models-science',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchAethelRoute = ResearchAethelRouteImport.update({
  id: '/aethel',
  path: '/aethel',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchMorbiusRoute = ResearchMorbiusRouteImport.update({
  id: '/morbius',
  path: '/morbius',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchParallaxRoute = ResearchParallaxRouteImport.update({
  id: '/parallax',
  path: '/parallax',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchPrometheusRoute = ResearchPrometheusRouteImport.update({
  id: '/prometheus',
  path: '/prometheus',
  getParentRoute: () => ResearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/aethel': typeof AethelRoute
  '/consortium': typeof ConsortiumRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRouteWithChildren
  '/news/agentic-long-horizon-reasoning': typeof NewsAgenticLongHorizonReasoningRoute
  '/news/autonomous-drug-discovery': typeof NewsAutonomousDrugDiscoveryRoute
  '/news/causal-inference-quant-finance': typeof NewsCausalInferenceQuantFinanceRoute
  '/news/multimodal-foundation-models-science': typeof NewsMultimodalFoundationModelsScienceRoute
  '/research/aethel': typeof ResearchAethelRoute
  '/research/morbius': typeof ResearchMorbiusRoute
  '/research/parallax': typeof ResearchParallaxRoute
  '/research/prometheus': typeof ResearchPrometheusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/aethel': typeof AethelRoute
  '/consortium': typeof ConsortiumRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRouteWithChildren
  '/news/agentic-long-horizon-reasoning': typeof NewsAgenticLongHorizonReasoningRoute
  '/news/autonomous-drug-discovery': typeof NewsAutonomousDrugDiscoveryRoute
  '/news/causal-inference-quant-finance': typeof NewsCausalInferenceQuantFinanceRoute
  '/news/multimodal-foundation-models-science': typeof NewsMultimodalFoundationModelsScienceRoute
  '/research/aethel': typeof ResearchAethelRoute
  '/research/morbius': typeof ResearchMorbiusRoute
  '/research/parallax': typeof ResearchParallaxRoute
  '/research/prometheus': typeof ResearchPrometheusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/aethel': typeof AethelRoute
  '/consortium': typeof ConsortiumRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRouteWithChildren
  '/news/agentic-long-horizon-reasoning': typeof NewsAgenticLongHorizonReasoningRoute
  '/news/autonomous-drug-discovery': typeof NewsAutonomousDrugDiscoveryRoute
  '/news/causal-inference-quant-finance': typeof NewsCausalInferenceQuantFinanceRoute
  '/news/multimodal-foundation-models-science': typeof NewsMultimodalFoundationModelsScienceRoute
  '/research/aethel': typeof ResearchAethelRoute
  '/research/morbius': typeof ResearchMorbiusRoute
  '/research/parallax': typeof ResearchParallaxRoute
  '/research/prometheus': typeof ResearchPrometheusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/aethel'
    | '/consortium'
    | '/publications'
    | '/research'
    | '/news/agentic-long-horizon-reasoning'
    | '/news/autonomous-drug-discovery'
    | '/news/causal-inference-quant-finance'
    | '/news/multimodal-foundation-models-science'
    | '/research/aethel'
    | '/research/morbius'
    | '/research/parallax'
    | '/research/prometheus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/aethel'
    | '/consortium'
    | '/publications'
    | '/research'
    | '/news/agentic-long-horizon-reasoning'
    | '/news/autonomous-drug-discovery'
    | '/news/causal-inference-quant-finance'
    | '/news/multimodal-foundation-models-science'
    | '/research/aethel'
    | '/research/morbius'
    | '/research/parallax'
    | '/research/prometheus'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/aethel'
    | '/consortium'
    | '/publications'
    | '/research'
    | '/news/agentic-long-horizon-reasoning'
    | '/news/autonomous-drug-discovery'
    | '/news/causal-inference-quant-finance'
    | '/news/multimodal-foundation-models-science'
    | '/research/aethel'
    | '/research/morbius'
    | '/research/parallax'
    | '/research/prometheus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AethelRoute: typeof AethelRoute
  ConsortiumRoute: typeof ConsortiumRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  NewsAgenticLongHorizonReasoningRoute: typeof NewsAgenticLongHorizonReasoningRoute
  NewsAutonomousDrugDiscoveryRoute: typeof NewsAutonomousDrugDiscoveryRoute
  NewsCausalInferenceQuantFinanceRoute: typeof NewsCausalInferenceQuantFinanceRoute
  NewsMultimodalFoundationModelsScienceRoute: typeof NewsMultimodalFoundationModelsScienceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aethel': {
      id: '/aethel'
      path: '/aethel'
      fullPath: '/aethel'
      preLoaderRoute: typeof AethelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consortium': {
      id: '/consortium'
      path: '/consortium'
      fullPath: '/consortium'
      preLoaderRoute: typeof ConsortiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/agentic-long-horizon-reasoning': {
      id: '/news/agentic-long-horizon-reasoning'
      path: '/news/agentic-long-horizon-reasoning'
      fullPath: '/news/agentic-long-horizon-reasoning'
      preLoaderRoute: typeof NewsAgenticLongHorizonReasoningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/autonomous-drug-discovery': {
      id: '/news/autonomous-drug-discovery'
      path: '/news/autonomous-drug-discovery'
      fullPath: '/news/autonomous-drug-discovery'
      preLoaderRoute: typeof NewsAutonomousDrugDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/causal-inference-quant-finance': {
      id: '/news/causal-inference-quant-finance'
      path: '/news/causal-inference-quant-finance'
      fullPath: '/news/causal-inference-quant-finance'
      preLoaderRoute: typeof NewsCausalInferenceQuantFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/multimodal-foundation-models-science': {
      id: '/news/multimodal-foundation-models-science'
      path: '/news/multimodal-foundation-models-science'
      fullPath: '/news/multimodal-foundation-models-science'
      preLoaderRoute: typeof NewsMultimodalFoundationModelsScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/aethel': {
      id: '/research/aethel'
      path: '/aethel'
      fullPath: '/research/aethel'
      preLoaderRoute: typeof ResearchAethelRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/morbius': {
      id: '/research/morbius'
      path: '/morbius'
      fullPath: '/research/morbius'
      preLoaderRoute: typeof ResearchMorbiusRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/parallax': {
      id: '/research/parallax'
      path: '/parallax'
      fullPath: '/research/parallax'
      preLoaderRoute: typeof ResearchParallaxRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/prometheus': {
      id: '/research/prometheus'
      path: '/prometheus'
      fullPath: '/research/prometheus'
      preLoaderRoute: typeof ResearchPrometheusRouteImport
      parentRoute: typeof ResearchRoute
    }
  }
}

interface ResearchRouteChildren {
  ResearchAethelRoute: typeof ResearchAethelRoute
  ResearchMorbiusRoute: typeof ResearchMorbiusRoute
  ResearchParallaxRoute: typeof ResearchParallaxRoute
  ResearchPrometheusRoute: typeof ResearchPrometheusRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchAethelRoute: ResearchAethelRoute,
  ResearchMorbiusRoute: ResearchMorbiusRoute,
  ResearchParallaxRoute: ResearchParallaxRoute,
  ResearchPrometheusRoute: ResearchPrometheusRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AethelRoute: AethelRoute,
  ConsortiumRoute: ConsortiumRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRouteWithChildren,
  NewsAgenticLongHorizonReasoningRoute: NewsAgenticLongHorizonReasoningRoute,
  NewsAutonomousDrugDiscoveryRoute: NewsAutonomousDrugDiscoveryRoute,
  NewsCausalInferenceQuantFinanceRoute: NewsCausalInferenceQuantFinanceRoute,
  NewsMultimodalFoundationModelsScienceRoute:
    NewsMultimodalFoundationModelsScienceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
